### PR TITLE
feat: add tokio::Runtime::enter

### PR DESCRIPTION
**Pull request by TennyZhuang**
https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#method.enter

### CODE REVIEW

**Comment by TennyZhuang** [comment]
It seems that we can `madsim::spawn` without any initialization operations? So I guess no-op here is OK.

**Review by wangrunji0408 — APPROVED** [review]
LGTM! Could you also help bump version to v0.2.23 and update the changelog? thx

**Comment by wangrunji0408** [comment]
Wait a moment. I found a problem. When a `Runtime` is dropped, all tasks spawned in it should also be cancelled. Therefore, `madsim::spawn` should find the current runtime first and store the task into it. However, this is not the case now, which means, if we create a runtime R, spawn a task A in R, and then spawn a new task B in A, B will not be dropped along with runtime R. This is a bug that should definitely be fixed. Would you rather fix it in this PR or enable this API first and then fix the problem later?

**Comment by TennyZhuang** [comment]
> Wait a moment. I found a problem. When a `Runtime` is dropped, all tasks spawned in it should also be cancelled. Therefore, `madsim::spawn` should find the current runtime first and store the task in it. However, this is not the case now, which means that if we create a runtime R, spawn a task A by `R.spawn()`, and then spawn a new task B in A using `madsim::spawn`, B will not be dropped along with runtime R. This is a bug that should definitely be fixed. Would you prefer to fix it in this PR or enable this API first and then fix the problem later?

It seems that the bug exists even without the PR?

**Comment by TennyZhuang** [comment]
> Yes. Let's fix it later.

Can you merge the PR and release a new version?

**Comment by wangrunji0408** [comment]
Sorry. forgot this 🤡

**Comment by wangrunji0408** [comment]
published as v0.2.24

**Pull request merged**
